export const tempSingleFileData = {
  'key-value': {
    Textracted_output: {
      'key-value': {
        Keys: {
          0: 'Received Date:',
          1: 'Serial Number:',
          2: 'Serial Number:',
          3: 'Branch Plant',
          4: 'Part Number Out:',
          5: 'Received Date:',
          6: 'Part Number',
          7: 'Outgoing Serial Number:',
          8: 'Orig. Prom. Date:',
          9: 'Customer PO#:',
          10: 'Agreement No.',
          11: 'Orig. Prom. Date:',
          12: 'Branch Plant',
          13: 'Customer Requested Warranty:',
          14: 'Customer PO#:',
          15: 'Nomenclature:',
          16: 'Incoming Visual:',
          17: 'Cert. Type:',
          18: 'JDE Cont:',
          19: 'Part Number',
          20: 'Incoming Visual:',
          21: 'Type:',
          22: 'Sold to#:',
          23: 'Ship to#',
          24: 'Customer Requested Warranty:',
          25: 'Agreement No.',
          26: 'Outgoing Serial Number:',
          27: 'Part Number Out:',
          28: 'Type:',
          29: 'Amendment No.',
          30: 'DPAS Rating:',
          31: 'Cust PO Date:',
          32: 'Amendment No.',
          33: 'Requested Date',
          34: 'Cont No.',
          35: 'Customer P/N In:',
          36: 'Cust PO Date:',
          37: 'METER READS:',
          38: 'JDE Cont:',
          39: 'Outgoing NSN:',
          40: 'Configuration In:',
          41: 'Cert. Type:',
          42: 'Configuration Out:',
          43: 'Customer Line#:',
          44: 'NSN No:',
          45: 'Model:',
          46: 'Customer P/N Out:',
          47: 'Order Admin:',
          48: 'Model:',
          49: 'Order Admin:',
          50: 'Requested Date',
          51: 'Customer Line#:',
          52: 'Outgoing NSN:',
          53: 'Part Number',
          54: 'Serial Number:',
          55: 'Workscope:',
          56: 'Work Instructions:',
          57: 'Related',
          58: 'Source Inspection out',
          59: 'AMMFABJ',
          60: '04/09/12',
          61: '04/12/12',
        },

        Values: {
          0: '07/07/15',
          1: '870509',
          2: 'V80-E1276',
          3: 'SDREP',
          4: '160371-600',
          5: '03/09/12',
          6: '160371-600',
          7: '870509',
          8: '08/06/15',
          9: '8490135066R',
          10: '11-MSA-265',
          11: '04/08/12',
          12: 'SDREP',
          13: 'N',
          14: 'RO 131959',
          15: 'APU',
          16: 'ROTOR TURNS FREELY. NO FOREIGN OBJECT DAMAGE.',
          17: 'FAA8130',
          18: 'VALUE_NOT_FOUND',
          19: '4951799',
          20: 'BRUSHES WORN. COMMUTATOR WORN. STARTER MOTOR NEEDS PAINT.',
          21: 'M Maintenance Support Program',
          22: '2094064 COBHAM AVIATION SVCS (CB/UXNN)',
          23: '149209 HAMILTON SUNDSTRAND (CS/SDROT)',
          24: 'N',
          25: 'VALUE_NOT_FOUND',
          26: 'V80-E1276',
          27: '4951799',
          28: 'VALUE_NOT_FOUND',
          29: 'VALUE_NOT_FOUND',
          30: 'Nomenclature: MOTOR, STARTER Customer P/N Out: Configuration Out:',
          31: 'VALUE_NOT_FOUND',
          32: 'VALUE_NOT_FOUND',
          33: '04/08/12',
          34: 'VALUE_NOT_FOUND',
          35: 'VALUE_NOT_FOUND',
          36: 'VALUE_NOT_FOUND',
          37: '15181 HOURS; 37238 STARTS.',
          38: 'VALUE_NOT_FOUND',
          39: 'VALUE_NOT_FOUND',
          40: 'MODS:86,125,138,153,164,173,174,175,196.',
          41: 'VALUE_NOT_FOUND',
          42: 'VALUE_NOT_FOUND',
          43: 'VALUE_NOT_FOUND',
          44: 'VALUE_NOT_FOUND',
          45: 'VALUE_NOT_FOUND',
          46: 'VALUE_NOT_FOUND',
          47: 'Kendra Scott',
          48: '46C2-APU',
          49: 'NSA',
          50: '08/06/15',
          51: 'VALUE_NOT_FOUND',
          52: 'VALUE_NOT_FOUND',
          53: '4951799',
          54: '3197-546',
          55: 'REPAIR (LEVEL: 2)',
          56: 'VALUE_NOT_FOUND',
          57: 'Order/Type 07083567 WW',
          58: 'VALUE_NOT_FOUND',
          59: '06/06/12',
          60: 'AMMFARR',
          61: 'AMMFABJ',
        },
      },

      text: [
        [
          'page_1',

          [
            'Part Number 160371-600',
            'Serial Number: 870509',
            'Customer PO#: 8490135066R',
            'Customer Line#:',
            'Order Admin: KKS',
            'Kendra Scott',
            'Branch Plant',
            'SDREP',
            'Orig. Prom. Date:',
            '08/06/15',
            'Requested Date 08/06/15',
            'Received Date: 07/07/15',
            'Cont No.',
            'Customer Requested Warranty: N',
            'JDE Cont:',
            'Agreement No.',
            'Amendment No.',
            'Type:',
            'Configuration In:',
            'MODS:86,125,138,153,164,173,174,175,196.',
            'Cust PO Date:',
            'METER READS: 15181 HOURS; 37238 STARTS.',
            'NSN No:',
            'DPAS Rating:',
            'Priority: 0 Routine Order',
            'Model:',
            'Nomenclature: APU',
            'Customer P/N In:',
            'Customer P/N Out:',
            'Customer Serial#:',
            'Part Number Out: 160371-600',
            'Configuration Out:',
            'Outgoing Serial Number: 870509',
            'Outgoing NSN:',
            'Cert. Type:',
            'FAA8130',
            'Incoming Visual:',
            'ROTOR TURNS FREELY. NO FOREIGN OBJECT DAMAGE.',
            'TIMES',
            'IN',
            'OUT',
            'CYCLES',
            'IN',
            'OUT',
            'TT',
            '43000.25',
            '43000.25',
            'TCSN',
            '73952.00',
            '73952.00',
            'TSR',
            '5420.57',
            '0.00',
            'TCSR',
            '9713.00',
            '0.00',
            '-',
            'Part Number 4951799',
            'Serial Number: V80-E1276',
            'Customer PO#: RO 131959',
            'Sold to#:',
            '2094064 COBHAM AVIATION SVCS (CB/UXNN)',
            'Customer Line#:',
            'Ship to#',
            '149209 HAMILTON SUNDSTRAND (CS/SDROT)',
            'Order Admin: NSA',
            'Nader Ahmed',
            'Branch Plant',
            'SDREP',
            'Orig. Prom. Date:',
            '04/08/12',
            'Requested Date 04/08/12',
            'Received Date: 03/09/12',
            'Cont No.',
            'Customer Requested Warranty:',
            'N',
            'JDE Cont:',
            'Agreement No. 11-MSA-265',
            'Amendment No.',
            'Type:',
            'M Maintenance Support Program',
            'Configuration In:',
            'Cust PO Date:',
            'NSN No:',
            'DPAS Rating:',
            'Priority: 0 Routine Order',
            'Model:',
            '46C2-APU',
            '55820',
            'Nomenclature: MOTOR, STARTER',
            'Customer P/N In:',
            'Customer P/N Out:',
            'Customer Serial#:',
            'Part Number Out: 4951799',
            'Configuration Out:',
            'Outgoing Serial Number: V80-E1276',
            'Outgoing NSN:',
            'Cert. Type:',
            'Incoming Visual:',
            'BRUSHES WORN.',
            'COMMUTATOR WORN.',
            'STARTER MOTOR NEEDS PAINT.',
            'TIMES',
            'IN',
            'OUT',
            'CYCLES',
            'IN',
            'OUT',
            'TT',
            '22802.10',
            '22802.10',
            'TCSN',
            '24897.00',
            '24897.00',
            'TSI',
            '2984.80',
            '2984.80',
            'TCSI',
            '2659.00',
            '2659.00',
          ],
        ],

        [
          'page_2',

          [
            'Part Number 4951799',
            'Serial Number: 3197-546',
            'Source Inspection out',
            'Related Work Order/Type',
            '07083567 WW',
            'Workscope: REPAIR (LEVEL: 2)',
            'Work Instructions:',
            '03/27/12 - WATKINR',
            '04/09/12 AMMFARR',
            '04/12/12 AMMFABJ',
            '04/16/12 LAAKSOS',
            '06/06/12 AMMFABJ',
          ],
        ],
      ],

      tables: {
        1: {
          schema: {
            fields: [
              {
                name: 'index',
                type: 'integer',
              },

              {
                name: 'TIMES',
                type: 'string',
              },

              {
                name: 'IN',
                type: 'string',
              },

              {
                name: 'OUT',
                type: 'string',
              },

              {
                name: 'CYCLES',
                type: 'string',
              },

              {
                name: 'IN',
                type: 'string',
              },

              {
                name: 'OUT',
                type: 'string',
              },
            ],

            primaryKey: ['index'],
            pandas_version: '0.20.0',
          },

          data: [
            {
              index: 1,
              TIMES: 'TT',
              IN: '73952.00',
              OUT: '73952.00',
              CYCLES: 'TCSN',
            },

            {
              index: 2,
              TIMES: 'TSR',
              IN: '9713.00',
              OUT: '0.00',
              CYCLES: 'TCSR',
            },
          ],
        },

        2: {
          schema: {
            fields: [
              {
                name: 'index',
                type: 'integer',
              },

              {
                name: 'TIMES',
                type: 'string',
              },

              {
                name: 'IN',
                type: 'string',
              },

              {
                name: 'OUT',
                type: 'string',
              },

              {
                name: 'CYCLES',
                type: 'string',
              },

              {
                name: 'IN',
                type: 'string',
              },

              {
                name: 'OUT',
                type: 'string',
              },
            ],

            primaryKey: ['index'],
            pandas_version: '0.20.0',
          },

          data: [
            {
              index: 1,
              TIMES: 'TT',
              IN: '24897.00',
              OUT: '24897.00',
              CYCLES: 'TCSN',
            },

            {
              index: 2,
              TIMES: 'TSI',
              IN: '2659.00',
              OUT: '2659.00',
              CYCLES: 'TCSI',
            },
          ],
        },

        3: {
          schema: {
            fields: [
              {
                name: 'index',
                type: 'integer',
              },

              {
                name: ' ',
                type: 'string',
              },

              {
                name: ' ',
                type: 'string',
              },

              {
                name: ' ',
                type: 'string',
              },
            ],

            primaryKey: ['index'],
            pandas_version: '0.20.0',
          },

          data: [
            {
              index: 1,
              ' ': '03/27/12 - WATKINR 04/09/12 AMMFARR 04/12/12 AMMFABJ 04/16/12 LAAKSOS 06/06/12 AMMFABJ',
            },

            {
              index: 2,
              ' ': ' ',
            },
          ],
        },
      },
    },

    Edited_output: {
      'key-value': {
        Keys: {
          0: 'Received Date:',
          1: 'Serial Number:',
          2: 'Serial Number:',
          3: 'Branch Plant',
          4: 'Part Number Out:',
          5: 'Received Date:',
          6: 'Part Number',
          7: 'Outgoing Serial Number:',
          8: 'Orig. Prom. Date:',
          9: 'Customer PO#:',
          10: 'Agreement No.',
          11: 'Orig. Prom. Date:',
          12: 'Branch Plant',
          13: 'Customer Requested Warranty:',
          14: 'Customer PO#:',
          15: 'Nomenclature:',
          16: 'Incoming Visual:',
          17: 'Cert. Type:',
          18: 'JDE Cont:',
          19: 'Part Number',
          20: 'Incoming Visual:',
          21: 'Type:',
          22: 'Sold to#:',
          23: 'Ship to#',
          24: 'Customer Requested Warranty:',
          25: 'Agreement No.',
          26: 'Outgoing Serial Number:',
          27: 'Part Number Out:',
          28: 'Type:',
          29: 'Amendment No.',
          30: 'DPAS Rating:',
          31: 'Cust PO Date:',
          32: 'Amendment No.',
          33: 'Requested Date',
          34: 'Cont No.',
          35: 'Customer P/N In:',
          36: 'Cust PO Date:',
          37: 'METER READS:',
          38: 'JDE Cont:',
          39: 'Outgoing NSN:',
          40: 'Configuration In:',
          41: 'Cert. Type:',
          42: 'Configuration Out:',
          43: 'Customer Line#:',
          44: 'NSN No:',
          45: 'Model:',
          46: 'Customer P/N Out:',
          47: 'Order Admin:',
          48: 'Model:',
          49: 'Order Admin:',
          50: 'Requested Date',
          51: 'Customer Line#:',
          52: 'Outgoing NSN:',
          53: 'Part Number',
          54: 'Serial Number:',
          55: 'Workscope:',
          56: 'Work Instructions:',
          57: 'Related',
          58: 'Source Inspection out',
          59: 'AMMFABJ',
          60: '04/09/12',
          61: '04/12/12',
        },

        Values: {
          0: '07/07/15',
          1: '870509',
          2: 'V80-E1276',
          3: 'SDREP',
          4: '160371-600',
          5: '03/09/12',
          6: '160371-600',
          7: '870509',
          8: '08/06/15',
          9: '8490135066R',
          10: '11-MSA-265',
          11: '04/08/12',
          12: 'SDREP',
          13: 'N',
          14: 'RO 131959',
          15: 'APU',
          16: 'ROTOR TURNS FREELY. NO FOREIGN OBJECT DAMAGE.',
          17: 'FAA8130',
          18: 'VALUE_NOT_FOUND',
          19: '4951799',
          20: 'BRUSHES WORN. COMMUTATOR WORN. STARTER MOTOR NEEDS PAINT.',
          21: 'M Maintenance Support Program',
          22: '2094064 COBHAM AVIATION SVCS (CB/UXNN)',
          23: '149209 HAMILTON SUNDSTRAND (CS/SDROT)',
          24: 'N',
          25: 'VALUE_NOT_FOUND',
          26: 'V80-E1276',
          27: '4951799',
          28: 'VALUE_NOT_FOUND',
          29: 'VALUE_NOT_FOUND',
          30: 'Nomenclature: MOTOR, STARTER Customer P/N Out: Configuration Out:',
          31: 'VALUE_NOT_FOUND',
          32: 'VALUE_NOT_FOUND',
          33: '04/08/12',
          34: 'VALUE_NOT_FOUND',
          35: 'VALUE_NOT_FOUND',
          36: 'VALUE_NOT_FOUND',
          37: '15181 HOURS; 37238 STARTS.',
          38: 'VALUE_NOT_FOUND',
          39: 'VALUE_NOT_FOUND',
          40: 'MODS:86,125,138,153,164,173,174,175,196.',
          41: 'VALUE_NOT_FOUND',
          42: 'VALUE_NOT_FOUND',
          43: 'VALUE_NOT_FOUND',
          44: 'VALUE_NOT_FOUND',
          45: 'VALUE_NOT_FOUND',
          46: 'VALUE_NOT_FOUND',
          47: 'Kendra Scott',
          48: '46C2-APU',
          49: 'NSA',
          50: '08/06/15',
          51: 'VALUE_NOT_FOUND',
          52: 'VALUE_NOT_FOUND',
          53: '4951799',
          54: '3197-546',
          55: 'REPAIR (LEVEL: 2)',
          56: 'VALUE_NOT_FOUND',
          57: 'Order/Type 07083567 WW',
          58: 'VALUE_NOT_FOUND',
          59: '06/06/12',
          60: 'AMMFARR',
          61: 'AMMFABJ',
        },
      },

      text: [
        [
          'page_1',

          [
            'Part Number 160371-600',
            'Serial Number: 870509',
            'Customer PO#: 8490135066R',
            'Customer Line#:',
            'Order Admin: KKS',
            'Kendra Scott',
            'Branch Plant',
            'SDREP',
            'Orig. Prom. Date:',
            '08/06/15',
            'Requested Date 08/06/15',
            'Received Date: 07/07/15',
            'Cont No.',
            'Customer Requested Warranty: N',
            'JDE Cont:',
            'Agreement No.',
            'Amendment No.',
            'Type:',
            'Configuration In:',
            'MODS:86,125,138,153,164,173,174,175,196.',
            'Cust PO Date:',
            'METER READS: 15181 HOURS; 37238 STARTS.',
            'NSN No:',
            'DPAS Rating:',
            'Priority: 0 Routine Order',
            'Model:',
            'Nomenclature: APU',
            'Customer P/N In:',
            'Customer P/N Out:',
            'Customer Serial#:',
            'Part Number Out: 160371-600',
            'Configuration Out:',
            'Outgoing Serial Number: 870509',
            'Outgoing NSN:',
            'Cert. Type:',
            'FAA8130',
            'Incoming Visual:',
            'ROTOR TURNS FREELY. NO FOREIGN OBJECT DAMAGE.',
            'TIMES',
            'IN',
            'OUT',
            'CYCLES',
            'IN',
            'OUT',
            'TT',
            '43000.25',
            '43000.25',
            'TCSN',
            '73952.00',
            '73952.00',
            'TSR',
            '5420.57',
            '0.00',
            'TCSR',
            '9713.00',
            '0.00',
            '-',
            'Part Number 4951799',
            'Serial Number: V80-E1276',
            'Customer PO#: RO 131959',
            'Sold to#:',
            '2094064 COBHAM AVIATION SVCS (CB/UXNN)',
            'Customer Line#:',
            'Ship to#',
            '149209 HAMILTON SUNDSTRAND (CS/SDROT)',
            'Order Admin: NSA',
            'Nader Ahmed',
            'Branch Plant',
            'SDREP',
            'Orig. Prom. Date:',
            '04/08/12',
            'Requested Date 04/08/12',
            'Received Date: 03/09/12',
            'Cont No.',
            'Customer Requested Warranty:',
            'N',
            'JDE Cont:',
            'Agreement No. 11-MSA-265',
            'Amendment No.',
            'Type:',
            'M Maintenance Support Program',
            'Configuration In:',
            'Cust PO Date:',
            'NSN No:',
            'DPAS Rating:',
            'Priority: 0 Routine Order',
            'Model:',
            '46C2-APU',
            '55820',
            'Nomenclature: MOTOR, STARTER',
            'Customer P/N In:',
            'Customer P/N Out:',
            'Customer Serial#:',
            'Part Number Out: 4951799',
            'Configuration Out:',
            'Outgoing Serial Number: V80-E1276',
            'Outgoing NSN:',
            'Cert. Type:',
            'Incoming Visual:',
            'BRUSHES WORN.',
            'COMMUTATOR WORN.',
            'STARTER MOTOR NEEDS PAINT.',
            'TIMES',
            'IN',
            'OUT',
            'CYCLES',
            'IN',
            'OUT',
            'TT',
            '22802.10',
            '22802.10',
            'TCSN',
            '24897.00',
            '24897.00',
            'TSI',
            '2984.80',
            '2984.80',
            'TCSI',
            '2659.00',
            '2659.00',
          ],
        ],

        [
          'page_2',

          [
            'Part Number 4951799',
            'Serial Number: 3197-546',
            'Source Inspection out',
            'Related Work Order/Type',
            '07083567 WW',
            'Workscope: REPAIR (LEVEL: 2)',
            'Work Instructions:',
            '03/27/12 - WATKINR',
            '04/09/12 AMMFARR',
            '04/12/12 AMMFABJ',
            '04/16/12 LAAKSOS',
            '06/06/12 AMMFABJ',
          ],
        ],
      ],

      tables: {
        1: {
          schema: {
            fields: [
              {
                name: 'index',
                type: 'integer',
              },

              {
                name: 'TIMES',
                type: 'string',
              },

              {
                name: 'IN',
                type: 'string',
              },

              {
                name: 'OUT',
                type: 'string',
              },

              {
                name: 'CYCLES',
                type: 'string',
              },

              {
                name: 'IN',
                type: 'string',
              },

              {
                name: 'OUT',
                type: 'string',
              },
            ],

            primaryKey: ['index'],
            pandas_version: '0.20.0',
          },

          data: [
            {
              index: 1,
              TIMES: 'TT',
              IN: '73952.00',
              OUT: '73952.00',
              CYCLES: 'TCSN',
            },

            {
              index: 2,
              TIMES: 'TSR',
              IN: '9713.00',
              OUT: '0.00',
              CYCLES: 'TCSR',
            },
          ],
        },

        2: {
          schema: {
            fields: [
              {
                name: 'index',
                type: 'integer',
              },

              {
                name: 'TIMES',
                type: 'string',
              },

              {
                name: 'IN',
                type: 'string',
              },

              {
                name: 'OUT',
                type: 'string',
              },

              {
                name: 'CYCLES',
                type: 'string',
              },

              {
                name: 'IN',
                type: 'string',
              },

              {
                name: 'OUT',
                type: 'string',
              },
            ],

            primaryKey: ['index'],
            pandas_version: '0.20.0',
          },

          data: [
            {
              index: 1,
              TIMES: 'TT',
              IN: '24897.00',
              OUT: '24897.00',
              CYCLES: 'TCSN',
            },

            {
              index: 2,
              TIMES: 'TSI',
              IN: '2659.00',
              OUT: '2659.00',
              CYCLES: 'TCSI',
            },
          ],
        },

        3: {
          schema: {
            fields: [
              {
                name: 'index',
                type: 'integer',
              },

              {
                name: ' ',
                type: 'string',
              },

              {
                name: ' ',
                type: 'string',
              },

              {
                name: ' ',
                type: 'string',
              },
            ],

            primaryKey: ['index'],
            pandas_version: '0.20.0',
          },

          data: [
            {
              index: 1,
              ' ': '03/27/12 - WATKINR 04/09/12 AMMFARR 04/12/12 AMMFABJ 04/16/12 LAAKSOS 06/06/12 AMMFABJ',
            },

            {
              index: 2,
              ' ': ' ',
            },
          ],
        },
      },
    },
  },
};
